### ISSUE TITLE
Error when parsing Mobx

### ISSUE THREAD

**Issue by jhnns** [callstack/linaria#1055]
## Environment

```sh
npm ls
├── @babel/core@7.18.13
├── @linaria/babel-preset@4.1.2
├── @linaria/core@4.1.1
├── @linaria/webpack-loader@4.1.2
├── babel-loader@8.2.5
├── webpack-cli@4.10.0
└── webpack@5.74.0
```

```sh
node -v
v16.13.1
```

On macOS Monterey

## Description

When I tried to update to the latest Linaria version, I ran into a strange parsing bug. Originally it failed on `dist/mobx.esm.js` from the popular MobX library.

I've boiled down the code to the following example:

```js
// main.js
import { css } from "@linaria/core";
import { b } from "./mobx.js";

css``;
```

```js
// mobx.js
var _;

var a = void _;

function b(b) {
  void _;
}

export { a, b };
```

When trying to parse this, it will fail with:

```sh
ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jhnns/dev/jhnns/linaria-bug-repo/src/main.js: /Users/jhnns/dev/jhnns/linaria-bug-repo/src/mobx.js: Exporting local "b", which is not declared.
  7 | }
  8 |
> 9 | export { a, b };
    |             ^
```

Could be a Babel bug, but since it only happens in conjunction with Linaria I guess this is the right place to start 😁 

## Reproducible Demo

The example is pretty small and simple:

https://github.com/jhnns/linaria-bug-repo

**Comment by Anber** [comment]
Hi @jhnns!

Well… a lot of things went wrong with your example :) The main problem here is that the `b` function is marked as dead code because its body becomes empty when `a` and all related code are removed.

First of all, `void _` inside `b` should not be deleted, but for some reason, Babel thinks that `_` in `var a = void _` is a binding identifier and not a referenced identifier, and since the binding is going to be deleted, all its references also should be deleted. 

Another problem here is how the function's name `b` is resolved as a reference of its own parameter `b` (`path.scope.getBinding(path.node.name)` surprisingly doesn't work well if `path` is an identifier of FunctionDeclaration).

I've fixed the problems, but I think both of them have nothing to do with your issues with `dist/mobx.esm.js` since it doesn't have any usages of `void` with identifiers. May I ask you to provide a broken repo with `mobx`?

**Comment by Anber** [comment]
The problem with MobX is deeper and much more complicated:
• `allowStateChanges` is removed because `allowStateChangesStart` is removed;
• `allowStateChangesStart` is removed because `globalState` is removed;
• `globalState` is removed because it uses `setTimeout` (that cannot be evaluated during compile-time) and `getGlobal` (that uses `window`).

I'll try to fix the shaker to ignore statements like `if (typeof window !== "undefined") return window`. The behaviour around `setTimeout` also looks fixable. However, there are another bigger problem which I want to fix in this issue. I can suppose, that you don't really need MobX for styles. May I ask you to check why `allowStateChanges` is used in your styles-related code? If it is used inside wrapped components, it should not affect Linaria, because all code inside components are stripped. Maybe there are usages inside some hooks or helper-functions? If so, may I see them?

**Comment by Anber** [comment]
I was wrong. The problem in MobX was only in function `allowStateChanges` with parameter `allowStateChanges`. Nice catch!
Anyway, `allowStateChanges` shouldn't be used by Linaria at all, so please let me know if you can check why it is used for styles.

**Comment by jhnns** [comment]
Awesome, thank you :)

`allowStateChanges` is used by `mobx-react-lite` which takes care of rerendering React components whenever Mobx observables change. Every React component will import `mobx-react-lite` which will import `allowStateChanges` from `mobx`. That's why this code is evaluated by Linaria.
