### ISSUE TITLE
Build linaria is very slow using webpack5 

### ISSUE THREAD

**Issue by magicismight** [callstack/linaria#1199]
## Environment

- Linaria version:
```
    "@linaria/babel-preset": "4.3.3",
    "@linaria/core": "4.2.5",
    "@linaria/react": "4.3.3",
    "@linaria/rollup": "4.3.2",
    "@linaria/shaker": "4.2.7",
    "@linaria/stylelint": "4.1.11",
    "@linaria/webpack-loader": "4.1.11",
```
- Bundler (+ version):
```
    "webpack": "5.75.0",
    "webpack-cli": "5.0.1",
    "webpack-dev-server": "4.11.1",
    "babel-loader": "8.2.3",
```
- Node.js version:
v14.17.0
- OS:
MacOS

## Description
Build with linaria in webpack5 would take 242275ms to build, in webpack4 only takes 66104ms
```
      {
        test: /\.js$/, 
        use: [{ loader: 'babel-loader' }]
      },
      {
        test: /\.tsx?$/,
        use: [
          { loader: 'babel-loader' },
          {
            loader: '@linaria/webpack-loader',
            options: {
              sourceMap: false
            }
          }
        ]
      },
```

**Comment by magicismight** [comment]
I have upgraded linaria from 
```
    "@linaria/babel-preset": "3.0.0-beta.15",
    "@linaria/core": "3.0.0-beta.18",
    "@linaria/react": "3.0.0-beta.18",
    "@linaria/rollup": "3.0.0-beta.15",
    "@linaria/shaker": "3.0.0-beta.7",
    "@linaria/stylelint": "3.0.0-beta.7",
    "@linaria/webpack-loader": "3.0.0-beta.7",
```
to @4.x.

linaria@4.x is way too much slower than linaria@3.x while using with webpack5, 3 or 4 times slower than linaria@3.x.

**Comment by TchernyavskyDaniil** [comment]
I had a similar problem. At beginning of introduction of version 4 of Linaria, we lost 4-5 times speed of project assembly
Next, we switched to swc-loader  

Here is simple config:
```ts
const swcOptions = {
  jsc: {
    parser: {
      syntax: "typescript",
      tsx: true
    },
    target: "es2018" // es2020 will of course give a better performance for assembly
  },
  env: {
    mode: "entry",
    coreJs: "3.28" // or another latest versions of core js
  }
}
```

For prod build I suggest looking at SwcMinifyWebpackPlugin

Next, for all style components, we have allocated the postfix `styled`. And Linaria - loader only looked at these files

```js
 {
    test: /\.?styled\.tsx?$/,
    exclude: /node_modules/,
    use: [
      {
        loader: "@linaria/webpack5-loader",
        options: {
          babelOptions: babelLinariaConfig // path to config
        }
      }
    ]
  },
```

Then I found a strange thing that even if you specify babelOptions, Linaria for some reason still used same generic babel - config (But we solved it, remained while moving to swc - loader)

Babel linaria config itself tried to do as much as possible for latest browsers, so that it takes less time to build (it all depends on your project of course)

```js
module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        useBuiltIns: "entry",
        corejs: 3.28,
        // Babel do not watch browserlist config, idk 
        targets:
          "last 1 Chrome version, last 1 Firefox version, last 2 Edge major versions, last 2 Safari major version, last 2 iOS major versions, Firefox ESR, not IE 9-11"
      }
    ],
    [
      "@babel/preset-react",
      {
        runtime: "automatic" // modern solution for React 17+
      }
    ],
    "@babel/preset-typescript",
    "@linaria"
  ]
}
```

Next, we separated the rules for css and for sass (yes, we still had the old modules on sass) 

```js
   {
      test: /\.css$/,
      use: [MiniCssExtractPlugin.loader, "css-loader"] // for dev maybe style-loader better for performance 
    },
     {
          test: /\.(scss|sass)$/,
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: "css-loader",
              options: {
                modules: "global"
              }
            },
            {
              loader: "postcss-loader",
              options: {
                postcssOptions: {
                  plugins: ["postcss-preset-env"]
                }
              }
            },
            {
              loader: "sass-loader",
              options: {
                sourceMap: false,
                implementation: require.resolve("sass")
              }
            }
          ]
        }
```

And we use filesystem webpack cache

After all this, we were able to reduce assembly time. Now, after implementing linaria, build time has increased by only 1.5 - 2 times (before improvements it was 4-5 times). I don't guarantee that you will get the same result (because some practices may just not work for you), plus if you have any other ideas, I would be happy to hear about

We were thinking about trying vite, but I'm still very confused by fact that Linaria also uses a babel plugin under the hood. Plus they still have MR open for filesystem cache. I think it's important with Linaria

The price of using CSS in JS and zero-runtime

**Comment by nstepien** [comment]
Digging into another issue, I found that linaria will trigger `@linaria/babel-preset/lib/transform-stages/helpers/loadLinariaOptions.js`'s `loadLinariaOptions` will **multiple times** on the **same files**.

In our codebase, one page may for example import a shared component via an import like
```ts
import { MyComponent } from 'components';
```
, which resolves to `src/components/index.ts` which re-exports all the shared components.
Linaria will then trigger babel to run on this file and everything that it re-exports.
These components may also import shared hooks/utils/types which also re-export hundreds of files.

@Anber If linaria only ran babel once on these files then it'd probably be fast, but in our case it transpiles nearly all of our codebase for every single module we have.
The solution would be to skip files it already handled.

**Comment by nstepien** [comment]
I found that moving `@linaria/webpack5-loader` above `babel-loader` in the `use` array made the build go from ~30 minutes to ~1 minute.

Though that makes webpack crash in dev mode with react refresh enabled:
```
ERROR in ./src/Root.tsx
Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):
EvalError: $RefreshSig$ is not defined in
| D:\repos\my-repo\src\Root.tsx

    at Module.evaluate (D:\repos\my-repo\node_modules\@linaria\babel-preset\lib\module.js:355:13)
    at evaluate (D:\repos\my-repo\node_modules\@linaria\babel-preset\lib\evaluators\index.js:20:5)
    at evalStage (D:\repos\my-repo\node_modules\@linaria\babel-preset\lib\transform-stages\2-eval.js:26:45)
    at syncStages (D:\repos\my-repo\node_modules\@linaria\babel-preset\lib\transform.js:47:45)
    at transform (D:\repos\my-repo\node_modules\@linaria\babel-preset\lib\transform.js:146:10)
```

**Comment by PierreGUI** [comment]
@Anber I'm starting to experience this issue now that my build is almost, it takes a very long time. Then when the build errors it exits early, I can imagine it's gonna take even longer when build error is fixed.

**What information can I provide to help you identify the root of the problem?**

Currently a build with `--progress` option shows this:
```
...
14% building 0/14 entries 2300/2322 dependencies 447/745 modules
20% building 1/14 entries 5242/5300 dependencies 990/1542 modules
49% building 10/14 entries 8201/8202 dependencies 2318/2362 modules
...
```

It already takes >7 minutes (`webpack 5.85.0 compiled with 3 errors in 428868 ms`), while a build with Linaria 2 (extractor strat) takes below 1 minute.

**Comment by Anber** [comment]
Hi @PierreGUI!

The v4 update brought about changes in the evaluation of a dependency tree, which means that the evaluator might attempt to evaluate a significant amount of redundant code. To investigate this, you can run the build with the DEBUG=linaria:* LINARIA_LOG=debug environment variables and examine the files that Linaria is processing. If you observe numerous files that are unrelated to styles, we can explore the reasons behind their inclusion and why they were not removed during the shaking process.

**Comment by Anber** [comment]
@nstepien nice catch! It looks like a lack of cache. I'll try to figure out something.

**Comment by PierreGUI** [comment]
@Anber Thanks for the pointers.  
I tried both debug variables and build just 1 (out of 12) module. The resulting log file has 4913189 lines (>300MB) 🙈 

# Problem A
- Turns out Linaria processes `node_modules/react/cjs/react.development.js`?! I assumed all my modules are processed.
- Thus, I wrote a rule to `ignore` everything in `node_modules`
- That doesn't work because I extend 3rd party components: `react-router`, `@mui`, `react-redux`, ...
- Tried to include those specific modules, while still excluding most of `node_modules`
- It's quite a tedious process (build fails, allow dependency to the rule, repeat), and the build still takes really long

```js
rules: [
	{
		test: /\/node_modules\//,
		action: 'ignore',
	},
	{
		test: /\/src|@mui|react-router|react-router-dom|@remix-run|react-redux|@linaria|@babel\//,
		action: require('@linaria/shaker').default,
	},
],
```

# Problem B
Browsing through the log file is cumbersome, due to its huge size and me not knowing anything of Linaria's internal processes.
I noticed multiple references to the same file, a lot. I understand the same file can be queued multiple times, but it it right the same file is "transformed" multiple times?  
For example, line like `linaria:transform:00005 [init] /path/src/reducers/index.ts (State)` appears 75 times. I found lines for different file that appear ±200 times. 
Not sure that's a thing worth investigating, I can dig this further if you want.

**Comment by Anber** [comment]
Well… it appeared, that both Webpack plugins just don't use cache at all.
