### ISSUE TITLE
Is dynamic imports supported?

### ISSUE THREAD

**Issue by oBusk** [callstack/linaria#193]
I'm trying to setup an enviroment using SSR and Code-splitting based on

* [`react-universal-component`](https://github.com/faceyspacey/react-universal-component)
* [`webpack-flush-chunks`](https://github.com/faceyspacey/webpack-flush-chunks)
* [`extract-css-chunks-webpack-plugin`](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin)

The code is written in typescript and built with webpack + babel.

As far as I can tell, the typescript should cause no issue (other than #192 ), but when I'm refering to imported constants in my linaria styles the linaria babel plugins are sptting out `Cannot find module './MyConstants'`.

The babel seems to run fine if I don't use Universal Component and instead import everything. Should it work with dynamic imports? Am i doing anything wrong?

**Comment by zamotany** [comment]
I don't think that dynamic imports will work, because some of your code will be evaluated in compile time in node context which doesn't implement `import` function, especially considering `import` is asynchronous.

Are you sure it was working w/o Universal Component, since linaria was never designed to work with TS, because we (internally for evaluation purposes) transpile the code with Babel not TypeScript.

**Comment by satya164** [comment]
> Am i doing anything wrong

Can you post a code sample?

**Comment by oBusk** [comment]
Thanks for the fast response!.

I'll gladly try to create a sample! I'll try to create one using typescript and one using Universal Component. I'll get back to you when I have it.

**Comment by oBusk** [comment]
Dynamic imports seems to be working when using `linaria/loader`! I created a [very rough setup](https://github.com/oBusk/react-universal-component-linaria) which seems to be working as expected. 

However, it seems like typescript is not working. [Here](https://github.com/oBusk/typescript-react-linaria) is a simple setup trying to build typescript and then run that through `linaria/loader` but when the CSS needs other components, linaria can't find them and fails. I've been trying to research if there's any way to output the result of the typescript loading as a step, but can't really find any. 

What would be needed for linaria to be able to handle something like this?

**Comment by ivan-aksamentov** [comment]
@oBusk Hi, Oscar, have you ever figured out how to make `linaria` to work with `react-universal-component` family, especially server-side rendering?  I checked your [react-universal-component-linaria](https://github.com/oBusk/react-universal-component-linaria), but it seems client side only.

**Comment by satya164** [comment]
@ivan-aksamentov can you post some code or error message on what you're encountering? is it a syntax error?

**Comment by ivan-aksamentov** [comment]
@satya164 Satyajit, thanks for asking! The answer ended up a bit long, because I am very new with linaria and my project requirements and setup are kinda weird.

At first I did not understand how `linaria` interacts with `extract-css-chunks-webpack-plugin` and `webpack-flush-chunks`. From docs I understood that linaria requires all CSS in a single file (or string in memory), while the other two packages split CSS, according to JS chunks. So I asked @oBusk right away if there is a ready-made solution.

Also, I just learned that `linaria/master` does not support Babel 7 yet, and learned about `linaria/next` branch. So I tried it and things seem to be magically working for simple setup so far, and it even combines styles from external .css files loaded by `extract-css-chunks-webpack-plugin` with CSS from jsx extracted by `linaria` itself. Super-cool!

Currently, it is unclear for me what is a good way to `collect()` the critical CSS on server. `webpack-flush-chunks` only provides names of .css file chunks. So I sketched this nonsense:

```
const { App } = createApp({ url })
const app = ReactDOM.renderToString(<App/>)

const chunkNames = flushChunkNames()

const {
  js,
  styles,
  cssHash,
  scripts,
  stylesheets,
} = flushChunks(clientStats, { chunkNames })

// Stupidly concat all the CSS. Kinda defeats the purpose of CSS-splitting.
const css = stylesheets.map(stylesheet => {
  return fs.readFileSync(path.join(clientStats.outputPath, stylesheet))
}).join('\n ')

const { critical, other } = collect(app, css)

let html = `<!DOCTYPE html>
  <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta http-equiv="X-UA-Compatible" content="ie=edge">
          <style type="text/css">${critical}</style>
          ${styles}
      </head>
      <body>
          <div id="app">${app}</div>
          ${cssHash}
          ${js}
      </body>
  </html>
```

And it works and indeed extracts critical CSS. 
There are problems though. On more complex setups the same code throws:

```
   TypeError: Cannot read property 'match' of undefined
       at node_modules/linaria/lib/server/collect.js:30:1
```

I'm still figuring out what is happening. I wonder if it is because of SCSS, or PostCSS loaders I'm using or, maybe linaria cannot handle full Bootstrap 4 monstrosity that `extract-css-chunks-webpack-plugin` pushes through. I will dig into it and report if I find out something specific.


Looking forward to developments in `next` branch.
Thanks for your work!

**Comment by satya164** [comment]
Thanks for the code. I'm not familiar with `collect` works, so I'll defer to @thymikee

**Comment by zamotany** [comment]
This should already work, if anyone have problem, please open separate issue.
