### ISSUE TITLE
Linaria webpack loader can't resolve webpack alias

### ISSUE THREAD

**Issue by consegrado** [callstack/linaria#284]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**

webpack config:
```
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      '@': `src/shared`,
    },
  },
```

file with linaria import:
```
import { css } from 'linaria';
import bp from '@/lib/breakpoints';
```

error:
```
Error: Module build failed (from ../node_modules/linaria/loader.js):
 SyntaxError: src/shared/components/TitleWithIcon/TitleWithIcon.styles.js: An error occurred when evaluating the expression: Cannot find module '@/lib/breakpoints'. Make sure you are not using a browser or Node specific API.
```

**Comment by zamotany** [comment]
This will be tricky to figure out, since even if we make it work with webpack, it will break in case of standalone babel compilation and CLI. That being said, I'm not sure if webpack provides a way to get all aliases resolved in a loader.

Currently the workaround is to use `babel-plugin-module-resolver`, which should work together with linaria.
