### ISSUE TITLE
Painfully slow performance during development

### ISSUE THREAD

**Issue by steffenmllr** [callstack/linaria#286]
I'm evaluating linaria for a upcoming project and setup a sample repo here: https://github.com/steffenmllr/linaria-ts-storybook

Long story short: If I add linaria to the project the compiling time for 2 sample components increases to a painfully slow startup time (`5s` to `14s`) which I might can live with but the rebuild time goes from instant `200ms` to `5142ms`.

So my question is: Is this a known issue or is my configuration wrong. Also can you point me in the direction where/why this is happening so I can help to improve it :) 

node `v8.14.0` with npm `6.4.1` and linaria `1.0.0-beta.2` see [package.json](https://github.com/steffenmllr/linaria-ts-storybook/blob/a43581271af614a9b20dbb159352cf00afd204f7/package.json#L12-L36)

**Comment by satya164** [comment]
Thanks a lot for the report. I did some investigation and it's because we are (unnecessarily) transpiling modules under `/node_modules/`. I just sent a PR which excludes `/node_modules/` by default and adds a config option to customize it. https://github.com/callstack/linaria/pull/287

Please try it and let me know if it improves the perf for you. I tested it locally and the slowdown is gone.

**Comment by steffenmllr** [comment]
Look much better. Saw that you missed the default `ignore` in https://github.com/callstack/linaria/pull/287/files#r245486139. When I added the node_modules regexp re-compilation is down to a couple of 100ms. The initial load time also went down to about 5-6sek.

Thank you!
