### ISSUE TITLE
linaria/loader don't work with ProvidePlugin

### ISSUE THREAD

**Issue by Dozalex** [callstack/linaria#319]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`linaria/loader` don't work if it used in webpack alias - no css bundle.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

webpack.config
```javascript
 new webpack.ProvidePlugin({
      React        : 'react',
      Component    : ['react', 'Component'],
      PureComponent: ['react', 'PureComponent'],
      PropTypes    : 'prop-types',
      styled       : ['linaria/react', 'styled'], // not work
      css          : ['linaria', 'css'], // not work
    }),
```

In components using `styled` and `css` without import.

**What is the expected behavior?**
linaria/loader works

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

.babelrc
```
{
  "presets": [["@babel/env", { "modules": false }], "@babel/react", "linaria/babel"],
  "plugins": [
    "react-hot-loader/babel",
    "@babel/plugin-proposal-class-properties",
    ["@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```
"linaria": "1.1.4",
"node": "11.5.0",
"yarn": "1.12.3",
macOS Mojave

**Comment by Dozalex** [comment]
@satya164 maybe need more info? It looks like #284 but with linaria alias

**Comment by zamotany** [comment]
Hey @Dozalex, thanks for reaching us.
The use case of yours is not actually a bug, it's a feature. When linaria is running babel to extract CSS, it checks if there's any import for `styled` or `css`. In that case there isn't - the JS that linaria has, doesn't have any import for `styled`/`css`. We can add option to disable a check, but then if some dependency is _provided_ with `ProvidePlugin` and also used inside `styled`/`css` interpolation it will fail, since linaria doesn't know that this dependency is _provided_.

We will try to research if we can get provided dependencies from Webpack or any information about those, which we can use, but if we cannot there's not much we can do about it.

**Comment by Anber** [comment]
Compatibility with webpack resolve plugins has been added in #830

**Comment by ionut-botizan** [comment]
Can you please re-open the issue? This still doesn't work.

The resolver options are not the same thing as the ProvidePlugin and they achieve different things:
* The resolver options tell Webpack how to resolve a package/path mentioned in an import
* The ProviderPlugin tells Webpack how to resolve a variable when there's no import at all
