### ISSUE TITLE
Any suggestions on how to test linaria styles in classes with Jest

### ISSUE THREAD

**Issue by skywickenden** [callstack/linaria#438]
I'm using react-testing-library and jest for testing. I'd like to write styling checks - either snapshots or individual styles.

I'm mainly using Linaria with css templates in React className attributes.

I'm not sure how to go about this. If I render the element with react-testing library then I can get access to the className, but not the actual styles as they are transpiled with babel. How are other people writing tests?

I found linaria-jest, however it only works with Linaria versions of < 1. Is there anything else out there? Or recommendations on the best way to go about linking the styles up in the test?

**Comment by skywickenden** [comment]
No worries. I've realized I can do it with [collect](https://github.com/callstack/linaria/blob/master/docs/API.md)

eg - quick and dirty: 

    import React from "react";
    import { render } from "../../test-utils";
    import Main from "./main";
    import { collect } from "linaria/server";
    import fs from "fs";
    import path from "path";
    const css = fs.readFileSync(path.resolve("./.linaria-cache/path/to/react/file/filename.linaria.css"), "utf8");

    it("Renders and has styles", () => {
      const { getByText } = render(<Main />);

      const content = getByText("Some text on the element being tested");
      const { critical, other } = collect(content, css);
      expect(critical).toEqual(expect.stringContaining("color:#872259"));
    });
Would be great if the css could be converted into an object, but this will do for now

**Comment by trongthanh** [comment]
I'm looking for some way to snapshot test the generated CSS and found this. But I am facing an issue that running `jest` alone won't make Linaria generate the intermediate CSS files in `./.linaria-cache/` folder. I have to start dev or build the project earlier in order to have the `*.linaria.css` files generated.

I'm just curious how you can do it if you can still recall?

**Comment by jasperkuperus** [comment]
I've just tried your approach @skywickenden, and it 'works'. But, it's far from foolproof. In my situation, I've got something along these lines:

```
<Button text="Click me" disabled={true} />
```

```
const normalStyles = css`
  cursor: pointer;
`;
const disabledStyles = css`
  cursor: not-allowed;
`,

function Button(props) {
  return <button className={cx(normalStyles), props.disabled && disabledStyles}>{props.text}</button>
}
```

If I use your approach, the critical CSS will give me:

```
.bc6yefj{cursor:pointer;}.d2aizej{cursor:not-allowed;}
```

If I would just use a `stringContaining` to check whether `cursor:not-allowed` is in there, it'd return `true`. But it'd also return `true` when I set `disabled={false}`. Because just all the possible styles which are critical for the button are in there.

Now, everything's in there. So I could check the `classNames` of the actual element you get by using `getByText`, cross reference that with the classes in the critical CSS, check whether the last applied `cursor` is indeed `not-allowed`. But then I'm practically writing a CSS parser...

Another route would be to export my classes, which are up till now internal to my Button component. I wouldn't prefer that approach, as that also ties my tests too much to my implementation. I don't want to know *how* this disabled styling is set, I just want to know whether a CSS behaviour is there that should be there for a disabled button.

Do you have input for us here @Anber ? Maybe an API that allows you to get the critical CSS as an object would already be a big help? I could walk through the classes list of an element back to front and check them within that object... Just thinking aloud here.

**Comment by Anber** [comment]
Hi @jasperkuperus
Since Linaria is zero-runtime, there is no way to check applied styles other than match class names. If you don't want to expose your classes, you can override the way how Linaria generates names in your test environment by setting `displayName` to `true` (or even specifying custom `classNameSlug`). So that you will be able to just check that Button has or has not the specific class `disabledStyles`.

**Comment by jasperkuperus** [comment]
Thanks for your explanation @Anber

**Comment by jasperkuperus** [comment]
Ok, I've made a very primitive code snippet to help me out here. Beware that it's very bare bones, no support for e.g. `:hover` states, no caching, no performance considerations... I had to jump through a few hoops to make TypeScript happy...

Basically, this reads the component's CSS stylesheet and classnames and applies the CSS rules in the order of applied classnames and then returns an object in the form of:

```css
{
  'background-color': '#98a4af',
  color: 'white',
  cursor: 'not-allowed',
  'font-weight': '400',
  padding: '10px 30px',
  'border-radius': '200px',
  border: 'none'
}
```

Here goes...

```ts
import { collect } from '@linaria/server';
import css from 'css';
import fs from 'fs';
import path from 'path';

/**
 * Returns the applied CSS rules for a given HTML element. You need
 * to pass in a rendered HTML element which contains the classnames
 * that are applied. As second argument you pass the path to the
 * component, so the stylesheet can be read, e.g.
 * `components/common/Button`.
 */
export function getAppliedCSS(
  element: HTMLElement,
  componentPath: string,
): Record<string, any> {
  // Read the linaria CSS file
  const compiledCSS = fs.readFileSync(
    path.resolve(`.linaria-cache/src/${componentPath}.linaria.css`),
    'utf8',
  );

  // Collect the critical CSS for this element and parse it
  const { critical } = collect(element.innerHTML, compiledCSS);
  const parsedCSS = css.parse(critical);

  // Split the classnames applied on this element
  const elementClasses = element.className.split(' ');

  // Loop over all class names
  const appliedCSS: Record<string, any> = {};
  for (const className of elementClasses) {
    // For each class name, find applicable rule in stylesheet
    for (const rule of parsedCSS.stylesheet?.rules ?? []) {
      if (
        rule.type === 'rule' &&
        'selectors' in rule &&
        rule.selectors?.includes(`.${className}`)
      ) {
        // Find all declarations of that rule
        for (const declaration of rule.declarations ?? []) {
          if (
            'property' in declaration &&
            'value' in declaration &&
            declaration.property != null
          ) {
            // Add each declaration to the applied CSS object
            appliedCSS[declaration.property] = declaration.value;
          }
        }
      }
    }
  }

  return appliedCSS;
}
```

Again, it's very bare bones. For me it now does what I need it to. You could easily expand and improve this. You'll probably have to change the path to the linaria cache to make it work for you.

This is how you'd use it in a test:

```ts
it('should apply disabled styling', () => {
  const handleClickStub = jest.fn();
  render(
    <Button text="Click me" disabled={true} onClick={handleClickStub} />,
  );

  // Assert button existence and disabled style
  const button = screen.getByText('Click me');
  const appliedStyles = getAppliedCSS(button, 'components/common/Button');
  expect(appliedStyles.cursor).toEqual('not-allowed');
});
```
