### ISSUE TITLE
:global css should be inserted before any other styles

### ISSUE THREAD

**Issue by nhooyr** [callstack/linaria#452]
Right now the `:global` are last.

I think this is unexpected as you can't use `:global` for global styles and then override some styles in specific components, the `:global` styles take precedence because they're last in the CSS file.

**Comment by satya164** [comment]
Linaria doesn't control insertion order. It depends on what code is loaded first. If your file containing the global CSS is the entry file or is imported in the entry file first, it'll be inserted first.

> I think this is unexpected as you can't use :global for global styles and then override some styles in specific components, the :global styles take precedence because they're last in the CSS file.

I think this is largely a non-issue because selectors (i.e. tags) in global styles have less specificity most of the time. It can be an issue with some, e.g. attribute selectors, but this can be controlled if you make sure that the file containing the global styles is imported first.

PR welcome to mention it in the docs.

**Comment by nhooyr** [comment]
> Linaria doesn't control insertion order. It depends on what code is loaded first. If your file containing the global CSS is the entry file or is imported in the entry file first, it'll be inserted first.

Makes sense but my global styles are in my index.tsx.

**Comment by nhooyr** [comment]
Any ideas why my global styles might be inserted last?

Full source at https://github.com/nhooyr/site/blob/3e2dd5306fc0535d69700a072574ae367014e418/src/index.tsx#L6

You can use `yarn && yarn dev` to start webpack-dev-server.

**Comment by nhooyr** [comment]
@satya164 could you reopen this issue until its figured out in case it is a bug with Linaria

**Comment by satya164** [comment]
@nhooyr Any ideas why my global styles might be inserted last?

Your CSS is code is loaded after your `App` is loaded. You can move it to another file and import it before you import `App`

**Comment by nhooyr** [comment]
Ohhh, of course. 🤦‍♂ thanks
