### ISSUE TITLE
1.4.0 release plans

### ISSUE THREAD

**Issue by Guria** [callstack/linaria#495]
## Ask your Question

What is plans to release 1.4.0? Can we have at least new alpha with `classNameSlug` option support?

**Comment by matiasbuildops** [comment]
Curious about this too (for `classNameSlug` support as well; to help with snapshot testing); there seems to be some activity (including bugfixes like #366) since the latest npm release, which is from March. 

Even a small update on the future plans would be much appreciated! 

ping @satya164 @thymikee ; perhaps you would be able to clarify? Thanks in advance and thanks for your work on what is already a great library!

**Comment by thymikee** [comment]
Latest beta was recently released: https://github.com/callstack/linaria/releases/tag/v1.4.0-beta.0. Please give it a try

**Comment by Guria** [comment]
@thymikee 
I am getting buid error with 1.4.0-beta.0:
```
node_modules/react-scripts/node_modules/@babel/runtime/helpers/esm/taggedTemplateLiteral.js:1
export default function _taggedTemplateLiteral(strings, raw) {
^^^^^^

SyntaxError: Unexpected token 'export'
```
