### ISSUE TITLE
Why when I load a page without javaScript I don't see the style file attached to the html?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [callstack/linaria#505]
My webpack config includes:  

 ```js
{
  ...
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'babel-loader',
            options: babelOptions(argv),
          },
          {
            loader: 'linaria/loader',
            options: { sourceMap: false, displayName: devMode, babelOptions: babelOptions(argv) },
          },
        ],
        exclude: /(node_modules)/,
      },
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
      ...
    ],
    plugins: [
        new MiniCssExtractPlugin({ filename: 'styles.css' }),
        ...
    ]
}
```

**Comment by resolritter** [comment]
Based on [this thread](https://github.com/callstack/linaria/issues/532#issue-553999445), I believe it's because the CSS files are dynamically required during runtime through JS. If that is correct, it makes sense for the CSS not to be written into the templated HTML file by default.

One idea for this case of runtime absence would be to resolve every output upfront and inject it directly into `index.html`, perhaps with some loader options.

**Comment by ShanonJackson** [comment]
Its probably because in dev mode style tags are injected dynamically into the head; In production mode the styles are outputted as build artifacts (given you have an appropriate loader).

If i understand the question correctly.

**Comment by jayu** [comment]
You should use an additional webpack plugin. Eg. https://www.npmjs.com/package/html-webpack-plugin
It will add `<link href="styles.css" rel="stylesheet"></head>` to your HTML output, for both development and production if you prefer.
