### ISSUE TITLE
Jest tests fail with moduleNameMapper config

### ISSUE THREAD

**Issue by 0xsven** [callstack/linaria#531]
## Environment
- MacOS: 10.14.6
- node: 12.14.1
- linaria: 1.3.1
- jest: 24.9.0
- react: 16.8.3

## Description
I have a `styled.*` component that uses a value, that was imported form another file:
```js
// component/ImportBox.js
import values from "layout/values";
const ImportBox = styled.div`
    background-color: ${values.a};
`;
export default ImportBox
```

The imported values are aliased with webpack resolve:
```js
webpack(config, options) {
    config.module.rules.push({
      test: /\.js$/,
      use: [ { loader: "linaria/loader" } ]
    });

    config.resolve.alias = {
      ...config.resolve.alias,
      layout: path.resolve(__dirname, "layout"),
      components: path.resolve(__dirname, "components")
    };
    return config;
  }
```

Aliases have been added to `jest.config.js` accordingly:
```js
moduleNameMapper: {
    "^layout(.*)$": "<rootDir>/layout$1",
    "^components(.*)$": "<rootDir>/components$1"
}
```

My jest test looks like that:
```js
// components/ImportBox.test.js
import React from "react";
import ReactDOM from "react-dom";

import ImportBox from "components/ImportBox"; // *

describe("Import Box", () => {
  it("renders without crashing", () => {
    const div = document.createElement("div");
    ReactDOM.render(<ImportBox />, div);
    ReactDOM.unmountComponentAtNode(div);
  });
});
```
`*` Note how I am using the alias to import the component.

When running the test with jest I am getting the following error message:
```Cannot find module 'layout/values'```

![Screen Shot 2020-01-21 at 16 11 34](https://user-images.githubusercontent.com/973379/72816626-c229b500-3c68-11ea-8841-056b5096573c.png)

**Can you please let me if I am doing something wrong?**

## Reproducible Demo
I am using next.js because it was the fastest way to create a Reproducible Demo from scratch.

Please clone and install the following git repo: https://github.com/0xsven/linaria-jest-alias-bug

- You can run `npm run dev` and will see two boxes rendered.
- When running `npm run test` you will execute two tests. One for each box. The box that uses an imported value will fail.

**Comment by SpawnAtis** [comment]
I have the similar problem only when running jest:

```js
import { baseTheme } from '../../../../theme';
// baseTheme is an object of constants

const StyledOption = styled.li`
   ....someStyles,
    &:hover {
        background-color: ${baseTheme.colors.B50};
    }
`;
```


<img width="1206" alt="Screen Shot 2020-03-13 at 19 46 42" src="https://user-images.githubusercontent.com/23311140/76641922-68a47f00-6563-11ea-8ea7-c4ea30417574.png">

**Comment by martshaw** [comment]
Moving from webpack resolve alias to babel-plugin-module-resolver fixes this problem. 

Please see https://github.com/0xsven/linaria-jest-alias-bug/pull/1 for any details.

**Comment by 0xsven** [comment]
@martshaw 's solution is a useful workaround for this issue. And it unblocks me from testing my components.

**Comment by jayu** [comment]
The reason why it happens is that Linaria has to evaluate some subset of sources to extract values. If you use aliasing in webpack or jest, your paths would be invalid for linaria because they will not be transformed yet.
I'm surprised that `babel-plugin-module-resolver` helps with it because we force linaria to be run before any other plugins. But it probably uses your babel config during evaluation and makes it works. @satya164 could you give more context about how linaria babel plugin is prioritized compared to other plugins? 
But using webpack or jest aliasing is not possible so we cannot address the issue

**Comment by Anber** [comment]
Actually, we are trying to use aliases from webpack, but probably something went wrong here. I would recommend to keep it open for future investigation.

**Comment by jayu** [comment]
I can confirm that aliases work in webpack, so it is only `Jest` issue

**Comment by thymikee** [comment]
Does this happen with Jest 25? I'd consider using babel plugin for import replacement, which would allow you to apply it once for various tooling

**Comment by jayu** [comment]
@thymikee `babel-plugin-module-resolver` is known workaround, however, people complain that is terribly slow https://github.com/callstack/linaria/issues/390#issuecomment-486669256. I'm curious if it is because of linaria, or because of the plugin

**Comment by TMaszko** [comment]
Plugins run before presets, thats why babel-plugin-module-resolver is working

**Comment by thymikee** [comment]
Transforms are cached, so that shouldn't be a problem, unless run on CI or without cache (which is not optimal). Other than that, without the plugin, Linaria would need to have its own mapper, since it needs to have a correct path for evaluation, which is outside of Jest scope

**Comment by satya164** [comment]
Maybe Linaria can cache evaluations too?

**Comment by jayu** [comment]
After some research, we decided to not support any kind of module aliasing than `@babel-plugin-module-resolver` and webpack aliases. It will require a lot of work to support aliasing from typescript, jest, and some other solutions that we did not discover yet. 
`@babel-plugin-module-resolver` works out of the box, because it operates on the babel level. Some people complain about the performance in tests, but we cannot do much about it. 

I opened an issue to document the status of module aliasing and give a solution for Typescript paths and Jest module mapper using module resolver plugin #630
