### ISSUE TITLE
[1.3.2] core-js resolving exception

### ISSUE THREAD

**Issue by pavelgrinchenko** [callstack/linaria#539]
## Environment

I'm using linaria as webpack plugin in Gatsby

## Description

After updating to the latest 1.3.2 version I get such error

```
Can't resolve 'core-js/modules/es.array.filter' in 'node_modules/linaria/lib/core'

File: node_modules/linaria/lib/core/cx.js
```

Seems it somehow depends on these changes https://github.com/callstack/linaria/commit/c67f40d8e9bd4950450288decb0a0a29d6e4cff0

**Comment by Anber** [comment]
@pavelgrinchenko thank you for your report!
I don't know why core-js decides that `es.array.filter` is needed here. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter `Array.proptotype.filter` is fully supported since IE9, so I've just added it to the exclude list.

**Comment by Anber** [comment]
Btw, `core-js` is a dependency, why it's cannot be resolved in your setup? I ask because probably there is the same issue with `styled` (which requires `es.array.index-of`), but I cannot reproduce it locally.

**Comment by pavelgrinchenko** [comment]
@Anber  I don't know. `core-js` listed as dependency in `linaria`'s package.json and it had to be resolved by package manager. But I had not time to dive into reasons...
