### ISSUE TITLE
css unicode characters fail

### ISSUE THREAD

**Issue by nodabladam** [callstack/linaria#548]
## Environment
Next.js 9.2.3-canary.13
Linaria 1.4.0-beta.3
Windows 10 and Zeit Now deployment

## Description

css unicode characters fail:
```
  ul.feedback-tip-lists li::before {
    content: "\2022";
  }
```
error
```
./.linaria-cache/src/components/feedback/FeedbackResponse/FeedbackResponse.scss.linaria.css
SassError: property "null" must be followed by a ':'
        on line 1488 of \frontend-v2\.linaria-cache\src\components\feedback\FeedbackResponse\FeedbackResponse.scss.linaria.css
>> .f160mpqf {null}

   -----------^
```

The linaria.css file in cache directory just has this
```
.f160mpqf {null}
``` 

note this works:
```
  ul.feedback-tip-lists li::before {
    content: "•";
  }
```

Here is the config (preprocessor disabled so I can use scss):
```
    config.module.rules.push({
      test: /\.js$/,
      exclude: ["/node_modules/"],
      use: [
        {
          loader: "linaria/loader",
          options: {
            preprocessor: "none",
            sourceMap: process.env.NODE_ENV !== "production"
          }
        }
      ]
    });
```

**Comment by Anber** [comment]
Hi @nodabladam 
I don't sure, but it's probably because you are trying to use the wrong way of character representation. If you try to evaluate your template string in a browser, you get an error `Octal escape sequences are not allowed in template strings.`. You can find more about Unicode in template strings [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).
As a solution, you can try to add `u` to the symbol code (`\u2022`). It may help.

**Comment by nodabladam** [comment]
Hmmm...`\u2022` does work.  Generally using strings like `\2022` for bullet in css is commonly accepted as the way to do it.  I can get behind `\u2022` vs raw `•` with linaria though.  Will close for now.  Thanks for the acceptable workaround.
