### ISSUE TITLE
Style conflicts when providing a className to a styled component

### ISSUE THREAD

**Issue by Jayphen** [callstack/linaria#549]
## Description

When applying a className to a styled component, it is possible for the styles defined by that styled component to override those defined by the passed-in class. This depends on the source ordering .

For example:

```jsx
const styles = css`
  font-size: 12px;
`;

const Title = styled.h1`
  font-size: 48px;
`;

<Title className={styles}>I will always be 48px</Title>
```

If a className is passed to a styled component, I would expect its styles to have higher specificity than the styled component's own styles.

## Reproducible Demo

I created a repo that shows the issue and a userland solution here https://github.com/Jayphen/linaria-playground/blob/master/src/App.js

The output looks like this:

```css
    .sm0as6w{font-size:12px;}
    .o13mnax5.o13mnax5{font-size:12px;}
    .tbb0x40{font-family:sans-serif;font-size:48px;color:red;}
```

The first class is overridden by the styled component's own styles (on line 3).

The second class is generated because of the use of the `&&` selector. The specificity is doubled, so the style does get applied.

The third class is the one generated by the styled component itself.

Perhaps therein lies a solution — any className passed to the `className` prop of a styled component should result in a duplicate selector (`.class.class`). I can't think of a better solution right now.

Other options —

- use data attributes instead of class names for styled components. Those have lower specificity.
- somehow hoist styled components classnames so they appear in the output css before all other style definitions. This won't solve the problem if the app is code splitting css though

**Comment by satya164** [comment]
`css` tags are an abstraction over class names, so all the same properties of using class names will apply here, including the cascade. The only way to avoid cascade is to use `styled(Title)` rather than vanilla class names, which seems reasonable to use here imo.

The workarounds might work only in specific situations or may not work at all or will be hard to implement. Data attributes may work for this, but imo it's weird to use them to fit a single use case of passing class name from Linaria to styled with Linaria when an alternative built in solution exists (styled(Title)).

Even if the cascade applies here, it's a predictable algorithm and will always result in predictable output, so easy to work around (for example using duplicated selector, or for third party styles, making sure that they are loaded last).

**Comment by Jayphen** [comment]
I understand the reasoning (parity with native className behaviour), however this differs from how emotion/SC handle things, so it's a bit of a blocker when migrating from one of those libraries, as I am. Unless you know the inner workings of Linaria, I don't think the current behaviour is totally expected. 

I'll have to think about this a bit more to figure out if it will be possible to codemod the above scenario. I'm in the process of migrating 100+ apps to Linaria from Emotion, so manually implementing a userland fix is not really possible.

**Comment by satya164** [comment]
SC doesn't have a separate class name feature though. How does it work differently in SC?

Emotion can work around it in a reliable way because it can know the order of two class names in runtime and then merge 2 styles to avoid cascade.

We could implement build time static analysis to determine that in Linaria, but it won't catch all cases, and in case if cross file analysis it could increase the build time a lot. It still wouldn't be reliable like the cascade which is a predictable algorithm.

I don't think you have to know Linaria internals to know why this happens. You need to know how cascade works and that styled adds a class name, both of which don't need any knowledge of internals.

It's not ideal, but for a build time tool I think it's a bit too much to understand the usage of the program and adjust output accordingly.

**Comment by Jayphen** [comment]
> it's a predictable algorithm and will always result in predictable output

This is not really the case — if you use a className that happens to be defined after the `styled` component, the styles of that className will apply. If you define the className first, the styles won’t apply. I don’t think this is entirely intuitive.

**Comment by Jayphen** [comment]
>SC doesn't have a separate class name feature though. How does it work differently in SC?

I'm not necessarily talking about the class name feature, just passing a class (from wherever it originates) as the className prop to a component.

I admit I don't know how it works in SC as I've not used it for a few years, but assume it works the same as in Emotion. Now that I'm looking in to it, they have a [warning about this behaviour in their docs](https://styled-components.com/docs/advanced#issues-with-specificity).

I suppose that in their case, given they don't have a `css` fn, it's less likely for this to be an issue.

Anyway, perhaps you're right and it's best dealt with in userland. I'll look in to this more tomorrow.

**Comment by Jayphen** [comment]
I think one userland solution for this could be a linting rule that re-orders `styled` and `css` declarations in any module, ensuring that the `css` declarations come last

**Comment by Jayphen** [comment]
I am closing this — I will write a lint rule that as above. I'll post it here when done in case anyone else needs it.

**Comment by mmakarin** [comment]
@Jayphen Any updates?
