### ISSUE TITLE
CSS Styles declared in `styled` with the ternary operator of props doesn't work. 

### ISSUE THREAD

**Issue by lzhuor** [callstack/linaria#648]
## Environment

- Linaria version: 2.0.0-alpha.5
- Bundler (+ version): Webpack (v4)
- Node.js version: v10.20.1
- OS: Mac OSX

## Description
CSS Styles declared in `styled` with the ternary operator of props doesn't work. 

## Reproducible Demo

```jsx
const Link = styled.a`
    ${props => props.showArrow ? `
        ::after {
            font-family: 'icomoon';
            content: '\\e908';
            margin-left: 1.2rem;
            align-self: center;
         }` : ''}
`
```

**Comment by Anber** [comment]
Hi @lzhuor!

Currently, it's possible to use functions only as property values, because all dynamic styles are transpiled into CSS variables and your `Link` class will look like this:
```
.Link_l1qwerty {
  var(--l1qwerty-0);
}
```
As you can see, it's invalid CSS. 

You can find a discussion about fragments [here](https://github.com/callstack/linaria/issues/244)
