### ISSUE TITLE
Update stylis.js dependency to v4

### ISSUE THREAD

**Issue by vladshcherbin** [callstack/linaria#649]
## Describe the enhancement

Since 2.0 is coming, maybe it's not too late to update `stylis.js` dependency to v4.

## Motivation

There might be improvements in different areas as well as breaking changes.

## Possible implementations

Update `stylis.js` and hope tests pass 🙈 

## Related Issues

https://github.com/callstack/linaria/issues/582

**Comment by Anber** [comment]
I've found at least one small BC… 4.0 just doesn't have an API which we used :) 
The repo also doesn't have a changelog or something similar, so I think, it's not safe to upgrade it right now.

**Comment by agriffis** [comment]
This might help: https://github.com/thysultan/stylis/issues/213

**Comment by agriffis** [comment]
It looks like @ludofischer updated his fork to use stylis v4, see commit linked above.

I'd like to see this in linaria proper, especially because stylis v4 fixes bugs I care about:

**stylis v3**

```
> const stylis = require('stylis')
> stylis('', '.a { :is(.b) { color: green; } }')
'.a:is(.b){color:green;}'
```

**stylis v4**

```
> const {compile, serialize, stringify} = require('stylis')
> serialize(compile('.a { :is(.b) { color: green; } }'), stringify)
'.a :is(.b){color:green;}'
```

</td></tr></table>

Note `.a:is()` versus `.a :is()`. To get the expected result on stylis v3, you need to constantly include `*` or `&` in places where you normally wouldn't need to in something like SASS.
