### ISSUE TITLE
Setup E2E test with the example app

### ISSUE THREAD

**Issue by zamotany** [callstack/linaria#65]

**Comment by thymikee** [comment]
Since we care about the looks as our end-to-end result, we could set up [Jest + Puppeteer](https://stackoverflow.com/questions/46818427/reusing-same-puppeteer-instance-in-all-jest-tests), save screenshots and compare them using [`jest-image-snapshot`](https://github.com/americanexpress/jest-image-snapshot) for example. 
Or we can set up Cypress too.

**Comment by zamotany** [comment]
Done in #148
