### ISSUE TITLE
Failed to install @linaria/webpack-loader

### ISSUE THREAD

**Issue by minhluuquang** [callstack/linaria#701]
## Environment

- Linaria version: 3.0.0-beta.0
- Bundler (+ version): Webpack 4.44.1
- Node.js version: 12.0.0
- OS: macOS 11.0.1

## Description

When trying to install dev dependeny @linarial/webpack-loader using  `npm install --save-dev @linaria/webpack-loader` but get error

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@linaria%2fwebpack-loader - Not found
npm ERR! 404 
npm ERR! 404  '@linaria/webpack-loader@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:npm ERR!     /Users/macintosh/.npm/_logs/2020-11-17T07_39_59_644Z-debug.log
```

**Comment by Anber** [comment]
Hi @minhluuquang 

I've made a wrong decision to rename `@linarial/webpack-loader` to `@linarial/webpack4-loader` in order to reserve `@linarial/webpack-loader` for the universal loader which will support both webpack 4 and 5. If you want to use `3.0` branch, you can currently use `@linarial/webpack4-loader`.

**Comment by ermik** [comment]
Update the README when you do such wonderful things.
