### ISSUE TITLE
Linara babel transform fails when the class name contains 'css'

### ISSUE THREAD

**Issue by maciejmyslinski** [callstack/linaria#712]
## Environment

- Linaria version: 3.0.0-beta.0
- Bundler (+ version): rollup 2.34.1
- Node.js version: 15.1.0
- OS: macos 10.15.7

## Description
Linara babel transform fails when the class name contains 'css'. Error message:
```
[!] (plugin linaria) SyntaxError: /Users/user-name/theme/src/prismjs.ts_k6975d.css: Unexpected token (1:0)

> 1 | .pu7lc9 .css{color:red;}
    | ^
```

**That's a super specific use case, can't you just use a different class name?**
No. I'm creating a prismjs theme and I specifically need `.language-css` class name.

## Reproducible Demo
```ts
css`
  .css {
    color: red;
  }
`;
```

**Comment by Anber** [comment]
Hi @maciejmyslinski!
It's the same problem https://github.com/callstack/linaria/issues/694
The fix for 3.0 will be released in the next beta on the next week. As a temporary solution, you can mark all css files [as ignored](https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options).
Sorry for the inconvenience.
