### ISSUE TITLE
swc support

### ISSUE THREAD

**Issue by morriq** [callstack/linaria#873]
https://swc.rs/ is fast babel alternative.

I tried to use linaria with that but without succes. Switched to emotion and it works out of the box.

**Comment by zetoke** [comment]
I guess it requires a kind of plugin to SWC for supporting this. 
But I'm curious about its support as well.
Especially since Next.js (Vercel) is moving towards using SWC as a default transpiling tool hence it's very wide adoption

**Comment by Anber** [comment]
Linaria is a babel plugin, so the support of SWC means that we have to rewrite everything to Rust and then support two different versions. Unfortunately, it seems impossible.

**Comment by Anber** [comment]
However, there is a chance, that SWC [will keep support for JS plugins](https://github.com/swc-project/swc/issues/2175). In that case, we will try to implement the plugin.

**Comment by theskillwithin** [comment]
Ya would be cool.  btw is there an example of how to setup with Next.js?  I mean do you have to do anything special like with styled-components needs this https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.js

**Comment by anulman** [comment]
I've been following this issue since it opened; nothing productive to add but another lib user's context and timeline:  I'm about to start on a new UI project, wanted to try out the latest Next updates, came to check in on this issue, and noticed I had already thumbs up'ed the above comment posted ~45 days ago.

While I appreciate the immense amount of work that goes into this project, I'm confused why the maintainers are silent here. I don't want to come off as entitled; it just looks like we're going to either have to lobby the referenced upstream issue or build something ourselves and would be good to do so as a community.

Meanwhile, `styled-components` has SWC support and a `collectStyles` method you can use in SSR. I'm going to try using that on this new project.

**Comment by austinbiggs** [comment]
I've come here to add similar sentiments to what @anulman has said above. I've been researching Styled Components alternatives and have all but decided to use Linaria in a new NextJS project. Due to the lack of SWC support, unfortunately, I'll need to consider alternatives (Compiled) with less ideal syntax.
